# Generated by Django 3.2.4 on 2021-06-14 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名前')),
                ('location', models.CharField(max_length=300, null=True, verbose_name='住所')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='電話番号')),
                ('gender', models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=2, null=True, verbose_name='性別')),
                ('birth_date', models.DateField(null=True, verbose_name='生年月日')),
                ('join_date', models.DateField(null=True, verbose_name='入会日')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='退会日')),
                ('arrive_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='時間')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.job')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.purpose')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.trigger')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
